version: '3.7'
services:
  pg:
    build:
      context: ../build/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=dev
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_MULTIPLE_DATABASES=auth profiles_manager
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - typerium:/var/lib/postgresql/data/pgdata
      - ../build/postgres/default_postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
volumes:
  typerium: